apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-dotnet
  namespace: dev
spec:
  selector:
    matchLabels:
      run: sample-dotnet
  replicas: 1
  template:
    metadata:
      labels:
        run: sample-dotnet
    spec:
      containers:
      - name: sample-dotnet
        image: 504572139667.dkr.ecr.ap-southeast-1.amazonaws.com/dev:latest
        ports:
        - name: sample-dotnet
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
