apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-dotnet
  namespace: dev
  labels:
    app: sample-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-dotnet-linux-app
  template:
    metadata:
      labels:
        app: sample-dotnet-linux-app
      containers:
      - name: nginx
        image: 504572139667.dkr.ecr.ap-southeast-1.amazonaws.com/dev:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
