apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-dotnet
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: nginx
        image: 504572139667.dkr.ecr.ap-southeast-1.amazonaws.com/dev:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
